#!/bin/bash
#
# Used to connect a host as an agent to Jenkins.

PROGRAM_NAME="$(basename "$0")"
# these env vars are for the AGENTOPTS_CFG_PATH
JENKINS_MAIN_URL=
JENKINS_AGENT_NAME=
JENKINS_USERNAME=
JENKINS_PASSWORD=
JENKINS_WORKINGDIR=
#
# NOTE: the agentops cfg file is to prevent jenkins credentials from being
# exposed when running the agent executable using the credentials by 
# viewing processes running on a system, for reference:
# https://issues.jenkins.io/browse/JENKINS-18342
# https://github.com/jenkinsci/remoting/blob/master/docs/inbound-agent.md#the--argument-annotation
AGENTOPTS_CFG_PATH="../configs/agentopts.cfg"
AGENT_JAR_FILENAME="agent.jar"

# heredoc that generates the cfg file
cat << _EOF_ > "$AGENTOPTS_CFG_PATH"
-jnlpUrl
${JENKINS_MAIN_URL}/computer/${JENKINS_AGENT_NAME}/jenkins-agent.jnlp
-jnlpCredentials
${JENKINS_USERNAME}:${JENKINS_PASSWORD}
-workDir
${JENKINS_WORKINGDIR}
_EOF_

if [ -z "$(which java)" ]; then
    echo "${PROGRAM_NAME}: java executable cannot be found on the PATH!"
    exit 1
fi

if [ -z "$(which wget)" ]; then
    echo "${PROGRAM_NAME}: wget cannot be found on the PATH!"
    exit 1
fi

if [ -z "$(find "$PWD" -maxdepth 1 -name "$AGENT_JAR_FILENAME")" ]; then
	if ! wget --quiet --output-document "$AGENT_JAR_FILENAME" "${JENKINS_MAIN_URL}/jnlpJars/${AGENT_JAR_FILENAME}"; then
        echo "${PROGRAM_NAME}: could not find/get the agent executable: ${AGENT_JAR_FILENAME}"
        exit 1
	fi
fi

java -jar "${AGENT_JAR_FILENAME}" @"${AGENTOPTS_CFG_PATH}" &

exit 0
