#!/bin/bash
#
# Used to connect a host as an agent to Jenkins.

set -e
PROGRAM_NAME="$(basename "$0")"
JENKINS_MAIN_URL=

# NOTE: the agentops cfg file is to prevent jenkins credentials from being
# exposed when running the agent executable using the credentials by 
# viewing processes running on a system, for reference:
# https://issues.jenkins.io/browse/JENKINS-18342
# https://github.com/jenkinsci/remoting/blob/master/docs/inbound-agent.md#the--argument-annotation
AGENTOPTS_CFG_PATH="../configs/agentopts.cfg"
AGENT_JAR_FILENAME="agent.jar"

if [ -z "$(which java)" ]; then
    echo "${PROGRAM_NAME}: java executable cannot be found on the PATH!"
    exit 1
fi

if [ -z "$(which wget)" ]; then
    echo "${PROGRAM_NAME}: wget cannot be found on the PATH!"
    exit 1
fi

if [ -z "$(find "$PWD" -maxdepth 1 -name "$AGENT_JAR_FILENAME")" ]; then
	if ! wget --quiet --output-document "$AGENT_JAR_FILENAME" "${JENKINS_MAIN_URL}/jnlpJars/${AGENT_JAR_FILENAME}"; then
        echo "${PROGRAM_NAME}: could not find/get the agent executable: ${AGENT_JAR_FILENAME}"
        exit 1
	fi
fi

java -jar "${AGENT_JAR_FILENAME}" @"${AGENTOPTS_CFG_PATH}" &

exit 0
